name: JUnit Tests
on: push
jobs:
  run_tests:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
